# -*- coding: utf-8 -*-
"""atividade 2 para mandar pro porfessor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1__Z93I5Np9TxWsJ9yj-FMFPjlVEbJgIM
"""

altura = float(input(""))
peso = float(input(""))

imc = peso / (altura * altura)

if imc < 16:
    print("Magreza grave")
elif imc < 17:
    print("Magreza moderada")
elif imc < 18.5:
    print("Magreza leve")
elif imc < 25:
    print("Saudável")
elif imc < 30:
    print("Sobrepeso")
elif imc < 35:
    print("Obesidade Grau I")
elif imc < 40:
    print("Obesidade Grau II (severa)")
else:
    print("Obesidade Grau III (morbida)")